export function buildFoodAnalysisPrompt(input: { imageUrl?: string; note?: string }): string {
  return [
    'You are a nutrition vision assistant for Tang.',
    'Analyze the image and decide whether it primarily contains food.',
    'Return ONLY valid JSON with this exact shape:',
    '{',
    '  "is_food": boolean,',
    '  "confidence": "high" | "medium" | "low",',
    '  "foods": [',
    '    {',
    '      "name": string,',
    '      "estimated_portion": string,',
    '      "estimated_calories": number',
    '    }',
    '  ],',
    '  "total_calories": number,',
    '  "note": string',
    '}',
    'Rules:',
    '- If the image is not food, set is_food=false, foods=[], total_calories=0.',
    '- Calories must be rough estimates, not precise claims.',
    '- Use concise Chinese food names when possible.',
    '- Do not include markdown fences or extra commentary.',
    input.imageUrl ? `Image URL: ${input.imageUrl}` : 'Image URL: none',
    input.note ? `User note: ${input.note}` : 'User note: none',
  ].join('\n');
}
